<?php

namespace Database\Seeders;

use App\Models\Artist;
use App\Models\Album;
use App\Models\Song;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BeyonceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
         // disable foreign key checks
         DB::statement('SET FOREIGN_KEY_CHECKS=0;');

         // truncate the table if it has data.
         DB::table('artists')->truncate();

         //Create Artist
         $beyonce = Artist::create([             
                 'name'=> 'Beyonce',
                 'image' => "https://t2.genius.com/unsafe/837x0/https%3A%2F%2Fimages.genius.com%2F25f7450d84a95225c33e8de77ce2c6b7.1000x1000x1.jpg", 
                 'bio' => "Beyoncé's musical story started when she was nine years old, spending time with a group of friends dancing and singing their way into vocal competitions and performing at the rodeo, local clubs and concert venues in Houston, Texas. The group of girls gradually morphed into becoming Destiny's Child, one of the most successful female recording groups of all-time. Destiny's Child amassed worldwide hits with both singles and albums and in 2001 BEYONCÉ became the first African-American woman and the second woman ever to take home the ASCAP Pop Songwriter of the Year Award for her work with the band. Following her success with Destiny's Child and making the change to becoming a solo artist, BEYONCÉ has become one of the defining artists of our generation. A singer, songwriter, performer, actor, filmmaker, Beyoncé is a creative tour-de-force who has captivated, astonished and is celebrated by the world."             
         ]);

          // Create Album linked to Artist
          
         // truncate the table if it has data.
         DB::table('albums')->truncate();
        $bday = Album::create([
            'title' => "B'Day",
            'year' => 2006,
            'image' => "https://m.media-amazon.com/images/I/816LJhBJIkL._SL1500_.jpg",
            'genre' => "Pop/R&B",
            'label' => "Sony",
            'rating' => 7.2,
            'artist_id' => $beyonce->id,
        ]);

          // Create Songs linked to Artist and Album
          
         // truncate the table if it has data.
         DB::table('songs')->truncate();
          $songsData = [
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ],
            [
                'title' => "Déjà Vu",
                'year' => 2006,
                'featuring' => "JAY-Z",
                'produced_by' => "Beyoncé, Rodney Jerkins",
                'written_by' => "Beyoncé, JAY-Z, Delisha Thomas, Makeba Riddick, Rodney Jerkins, Keli Nicole Price",
                'image' => "https://t2.genius.com/unsafe/278x278/https%3A%2F%2Fimages.genius.com%2F2b2977987396626f909aa7e15f24c896.300x300x1.png",
                'about' => "Consistency is a hallmark of the recorded work of Beyoncé. ",
                "music_video"=> "https://www.youtube.com/watch?v=nmP5CBiFigo",
                'artist_id' => $beyonce->id,
                'album_id' => $bday->id,
            ]
            // Add other song data as needed
        ];

        foreach ($songsData as $songData) {
            Song::create($songData);
        }

         // enable foreign key checks
         DB::statement('SET FOREIGN_KEY_CHECKS=1;');
    }
}
